[www]                       ; Pool Name

user = www-data             ; Unix user/group of processes
group = www-data
listen = 9000               ; NGINX send PHP request to port 9000
listen.owner = www-data     ; decides who has the permission to read and write socket
listen.group = www-data
pm = dynamic                ; Process Management Mode: dynamic(elastic number of PHP child process)
pm.max_children = 5         ; maximun 5 PHP process (determine server's concurrent processing power)
pm.start_servers = 2        ; when server just starts, 2 processes are waitting
pm.min_spare_servers = 1    ; at least 1 process waitting
pm.max_spare_servers = 3    ; maximun 3 spare processes waitting (save memory)
clear_env = no              ; so PHP can read global variables in .env
