server
{
    listen 80;
    listen [::]:80;
    server_name yopeng.42.fr;
    return 301 https://$host$request_uri;
}
server 
{
    # IPv4 IPv6 listeners for SSL 
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name yopeng.42.fr;
    # SSL certificate path & key generated in Dockerfile
    ssl_certificate /etc/nginx/ssl/localhost.pem;
    ssl_certificate_key /etc/nginx/ssl/-key.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    root /var/www/html;
    index index.php index.html index.htm;
    # default location block
    location / 
    {
        try_files $uri $uri/ /index.php?$args;
    }
    # pass PHP requests to WordPress container via FastCGI(listen port 9000)
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass wordpress:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}

