anonymous_enable=NO
local_enable=YES

# allow write-in command (upload, make directory...)
write_enable=YES

# umask: user mask (used to block permission)
# directory: 777 - 022 = 755 (rwx r-x r-x) (Makefile gives full permission to directory 777)
# file:      666 - 022 = 644 (rw- r-- r--)
local_umask=022

# xferlog: transfer log (when file operation occurs)
xferlog_enable=YES

# Active Mode: server connects to client via port 20 (The modern environment does not use it.) 
# (Passive Mode is the opposite)
connect_from_port_20=YES

# chroot: change root (user stays in /var/www/html, cannot access /var)
chroot_local_user=YES

# allow upload or edit WordPress files 
# (otherwise FTP will report error: "500 OOPS: vsftpd: refusing to run with writable root inside chroot()")
allow_writeable_chroot=YES

# Passive Mode: client connects to server via port 21
# 21100-21110:  ports provided by server for client to connect
# Modern FTP standard solution: Passive Mode (only client can connect to server, not the opposite)
pasv_enable=YES
pasv_min_port=21100
pasv_max_port=21110

# vsftpd runs in foreground (docker runs as PID1)
background=NO

# vsftpd_user goes to root directory
local_root=/var/www/html

# vsftpd goes to secure_chroot_dir for safety reason
# (empty, unwritable and safe sandbox directory)
secure_chroot_dir=/var/run/vsftpd/empty